"""Initial migration with all models

Revision ID: 0533e1bf90df
Revises: 92a9bc3a2dc9
Create Date: 2026-01-20 21:00:57.270882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0533e1bf90df'
down_revision = '92a9bc3a2dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('points_for', sa.Integer(), nullable=True),
    sa.Column('points_against', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
