"""Suppression du champ points dans la table team

Revision ID: 587c47ed8920
Revises: bd52ef83fd76
Create Date: 2026-01-21 13:59:29.153896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587c47ed8920'
down_revision = 'bd52ef83fd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
