"""Ajout du champ is_closed dans Match

Revision ID: bd52ef83fd76
Revises: cdb415d5e22a
Create Date: 2026-01-20 23:19:27.704052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd52ef83fd76'
down_revision = 'cdb415d5e22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=True))
        batch_op.alter_column('table_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('table_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###
