"""Ajout du champ table_number dans Match

Revision ID: cdb415d5e22a
Revises: 0533e1bf90df
Create Date: 2026-01-20 22:37:53.843295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb415d5e22a'
down_revision = '0533e1bf90df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('table_number')

    # ### end Alembic commands ###
